name = "Walnut Pack"
author = "RustedAperture"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8966db06f69404e0f86ab962e3b423c8d6be42d7a678734d3dd3e453e8b73c0"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0"
