name = "Walnut Pack"
author = "RustedAperture"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b92ff6b77f304b5e9fa5596895faf700d88c10dcad2e1debed6ef579090940b9"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0"
